// <auto-generated />
namespace AssetsDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_currency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_currency));
        
        string IMigrationMetadata.Id
        {
            get { return "202107111044351_add_currency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
